### ISSUE TITLE
Fails to build for manylinux

### ISSUE THREAD

**Issue by DarthNihilus1** [fireclawthefox/DirectGuiDesigner#6]
ERROR: Could not find a version that satisfies the requirement panda3d (from versions: none)
ERROR: No matching distribution found for panda3d
```
Traceback (most recent call last):
  File "D:\Github\DirectGuiDesigner\setup.py", line 10, in <module>
    setup(
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\dist\commands.py", line 436, in run
    self.build_runtimes(platform, True)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\dist\commands.py", line 596, in build_runtimes
    wheelpaths = self.download_wheels(platform)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\site-packages\direct\dist\commands.py", line 499, in download_wheels
    subprocess.check_call([sys.executable, '-m', 'pip'] + pip_args)
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Michael\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'download', '-d', 'D:\\Github\\DirectGuiDesigner\\build\\__whl_cache__\\manylinux1_x86_64_cp310', '-r', 'D:\\Github\\DirectGuiDesigner\\requirements.txt', '--only-binary', ':all:', '--abi', 'cp310', '--platform', 'manylinux1_x86_64', '--extra-index-url', 'https://archive.panda3d.org/simple/opt', '--extra-index-url', 'https://archive.panda3d.org/thirdparty']' returned non-zero exit status 1.
```

**Comment by rdb** [comment]
There are no manylinux1_x86_64 wheels for Python 3.10, use manylinux2010_x86_64 instead.

**Comment by fireclawthefox** [comment]
@DarthNihilus1 I guess this problem is solved, isn't it?

**Comment by rdb** [comment]
Well, you might want to change it in `setup.py`, either change it to `manylinux2010_x86_64` entirely or make it dependent on `sys.version_info >= (3, 10)`

**Comment by fireclawthefox** [comment]
Ah yes, thanks for the hint.
